const {PGlite} = await import(process.env.ORTHOBIBLE_PGLITE_MODULE || '@electric-sql/pglite');
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; grant usage on schema auth to authenticated; grant execute on function auth.uid() to authenticated; insert into auth.users values ('11111111-1111-4111-8111-111111111111'),('22222222-2222-4222-8222-222222222222');`);
await db.exec(fs.readFileSync(new URL('../cloud/schema.sql',import.meta.url),'utf8'));
await db.exec(`set role authenticated; set request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';`);
let result=await db.query(`select public.save_orthobible(0,'{"book":"JHN"}','{"data":{"notes":"private"}}') as saved`);
assert.equal(result.rows[0].saved.revision,1);
await assert.rejects(db.query(`select public.save_orthobible(0,'{}',null)`),/sync_conflict/);
result=await db.query(`select public.save_orthobible(1,'{"book":"GEN"}',null) as saved`);
assert.equal(result.rows[0].saved.revision,2);assert.equal(result.rows[0].saved.study_revision,1);
result=await db.query(`select personal from public.orthobible_sync`);
assert.equal(result.rows[0].personal.data.notes,'private');
await assert.rejects(db.query(`select public.save_orthobible(1,'{}',null)`),/sync_conflict/);
await db.exec(`set request.jwt.claim.sub='22222222-2222-4222-8222-222222222222';`);
assert.equal((await db.query('select * from public.orthobible_sync')).rows.length,0);
assert.equal((await db.query(`update public.orthobible_sync set reader='{}' where user_id='11111111-1111-4111-8111-111111111111' returning *`)).rows.length,0);
await assert.rejects(db.query(`insert into public.orthobible_sync(user_id,reader) values('11111111-1111-4111-8111-111111111111','{}')`),/row-level security/);
await db.exec(`reset role; set role anon;`);
await assert.rejects(db.query('select * from public.orthobible_sync'),/permission denied/);
await assert.rejects(db.query(`select public.save_orthobible(0,'{}',null)`),/permission denied/);
console.log('PASS: schema executes; owner-only reads/writes; anonymous denied; stale revisions rejected; unchanged OSB data retained.');
await db.close();
